############################
# Copyrightc 2022 FUJITSU LIMITED
# FileName: CFN-IRK-NW01_202212.yml
# FileType: YAML
# OverViews: CloudFormation Template for MNT Network
# Version: 1.0
# Author: Fujitsu - tokuzumi
############################

AWSTemplateFormatVersion: "2010-09-09"

Transform:
  Name: 'AWS::Include'
  Parameters:
    Location: !Sub '${MappingFilePATH}'

Parameters:
  #  ## user form  ##
  #  :param SystemNameUpper: 
  #  :param EnvironmentNameUpper:
  #  :param MappingFilePASS: 

  MappingFilePATH:
    Type: String
    Default: 'example: s3://'
  SystemNameUpper:
    Type: String
    Default: 'IRK'
    AllowedValues: ['OQS','IRK','TKK','YZK']
  SystemNameLower:
    Type: String
    Default: 'irk'
    AllowedValues: ['oqs','irk','tkk','yzk']
  EnvironmentNameUpper2:
    Type: String
    Default: 'MT2'
    AllowedValues: ['MNT','DEV','STG','PRO','MT1','MT2','ST1','ST2']
  EnvironmentNameLower2:
    Type: String
    Default: 'mt2'
    AllowedValues: ['mnt','dev','stg','pro','mt1','mt2','st1','st2']


Resources:

#------------------------SecurityGroup---------------------#
  #  ### ALB-WEB01  ###
  # SGforAlbBWEB01A:
  #   Type: 'AWS::EC2::SecurityGroup'
  #   Properties:
  #     GroupDescription: !Sub SG-ALB-${SystemNameUpper}-${EnvironmentNameUpper2}-WEB01-B
  #     GroupName: !Sub SG-ALB-${SystemNameUpper}-${EnvironmentNameUpper2}-WEB01-B
  #     VpcId: !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, VPCID]
  #     Tags:
  #       - Key: Name
  #         Value: !Sub SG-ALB-${SystemNameUpper}-${EnvironmentNameUpper2}-WEB01-B

#------------------Create ELB-----------------------------#

  #  ### NLB 001 A ###
  NLB001A:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Sub NLB-${SystemNameUpper}-${EnvironmentNameUpper2}-001-B
      Scheme: internal
      Type: network
      Subnets:
        - !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, SUBAFR01]
        - !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, SUBAFR02]
        - !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, SUBAFR03]
      IpAddressType: ipv4
      LoadBalancerAttributes: 
       - Key: 'access_logs.s3.enabled'
         Value: true
       - Key: access_logs.s3.bucket
         Value: !Sub s3-${SystemNameLower}-${EnvironmentNameLower2}-nlb-log
       - Key: access_logs.s3.prefix
         Value: !Sub NLB-${SystemNameUpper}-${EnvironmentNameUpper2}-001-B
       - Key: deletion_protection.enabled
         Value: true
       - Key: load_balancing.cross_zone.enabled
         Value: true

  #  ### ALB WEB01 A ###
  ALBWEB01A:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ALB-${SystemNameUpper}-${EnvironmentNameUpper2}-WEB01-B
      Scheme: internal
      Type: application
      Subnets:
        - !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, SUBWFR01]
        - !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, SUBWFR02]
        - !FindInMap [!Ref SystemNameUpper, !Ref EnvironmentNameUpper2, SUBWFR03]
      SecurityGroups:
       - sg-06d32c19a73071b84
      IpAddressType: ipv4
      LoadBalancerAttributes:
       - Key: access_logs.s3.enabled
         Value: false
       - Key: access_logs.s3.bucket
         Value: !Sub s3-${SystemNameLower}-${EnvironmentNameLower2}-alb-log
       - Key: access_logs.s3.prefix
         Value: !Sub ALB-${SystemNameUpper}-${EnvironmentNameUpper2}-WEB01-B
       - Key: idle_timeout.timeout_seconds
         Value: 60
       - Key: deletion_protection.enabled
         Value: true
       - Key: routing.http2.enabled
         Value: true
       - Key: routing.http.drop_invalid_header_fields.enabled
         Value: false
       - Key: routing.http.xff_client_port.enabled
         Value: false
       - Key: routing.http.preserve_host_header.enabled
         Value: false
       - Key: routing.http.xff_header_processing.mode
         Value: append
       - Key: load_balancing.cross_zone.enabled
         Value: true
       - Key: routing.http.desync_mitigation_mode
         Value: defensive
       - Key: waf.fail_open.enabled
         Value: false
       - Key: routing.http.x_amzn_tls_version_and_cipher_suite.enabled
         Value: false
