#############################################################
# Copyright 2019 FUJITSU LIMITED
# FileName: CLF-CICD-Template-LMD-From-3Kinou-To-OQS.yml
# FileType: YAML
# OverViews: CloudFormation Template for LMD-WEBECS CI/CD
# Version: 1.0
# Author: Fujitsu - hou
#############################################################

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  Name: 'AWS::Include'
  Parameters:
    Location: !Sub '${MappingFilePATH}'


Parameters:
  #  ## user form  ##
  #  :param ProjectNumber: [Example:'99999']
  #  :param NLBNumber: ['001','002','003','004','005','006','007','008','009']
  #  :param Port: [Example:'15000']
  #  :param SystemEnvironmentName: ['TKKDEV','TKKMNT','TKKSTG','IRKDEV','IRKMNT','IRKSTG','YZKDEV','YZKMNT','YZKSTG','OQSDEV','OQSMNT','OQSSTG']
  #  :param ExecutionRoleName: ['IAMR-TKK-DEV-WEBTaskAction01','IAMR-TKK-STG-WEBTaskAction','IAMR-IRK-MNT-WEBTaskAction','IAMR-IRK-MNT-WEBTaskAction02','IAMR-IRK-STG-WEBTaskAction','IAMR-YZK-STG-WEBTaskAction','IAMR-YZK-STG-WEBTaskAction02','IAMR-OQS-DEV-WEBTaskAction01','IAMR-OQS-DEV-WEBTaskAction02','IAMR-OQS-MNT-WEBTaskAction01','IAMR-OQS-MNT-WEBTaskAction02','IAMR-OQS-STG-WEBTaskAction01','IAMR-OQS-STG-WEBTaskAction02']
  #  :param TaskRoleName:  ['IAMR-TKK-DEV-WEBContainerAction01','IAMR-TKK-STG-APContainerAction','IAMR-IRK-MNT-APContainerAction','IAMR-YZK-MNT-APContainerAction','IAMR-YZK-MNT-APContainerAction02','IAMR-IRK-STG-APContainerAction','IAMR-YZK-STG-APContainerAction','IAMR-YZK-STG-APContainerAction02','IAMR-OQS-DEV-WEBContainerAction01','IAMR-OQS-DEV-WEBContainerAction02','IAMR-OQS-MNT-WEBContainerAction01','IAMR-OQS-MNT-WEBContainerAction02','IAMR-OQS-MNT-WEBContainerAction03','IAMR-OQS-STG-WEBContainerAction01','IAMR-OQS-STG-WEBContainerAction02','IAMR-OQS-STG-WEBContainerAction03']
  #  :param ClusterNumber: ['01','02']
  #  :param DesiredCount: EcsService Desired 
  #  :param MaxCapacity: ScalableTarget MAX   
  #  :param MinCapacity: ScalableTarget Min   
  #  :param TargetValue: ScalingPolicy 70
  #  :param BuildBucketName: ['tkk-build-source-bucket-dev1','irk-build-source-bucket-mnt','tkk-build-source-bucket-stg','build-source-bucket-dev','build-source-bucket-mnt','build-source-bucket-stg']
  #  :param BuildServiceRoleName: ['IAMR-TKK-DEV-WEBCodeBuild01','IAMR-TKK-STG-WEBCodeBuild','IAMR-IRK-MNT-WEBCodeBuild','IAMR-IRK-MNT-WEBCodeBuild02','IAMR-IRK-STG-WEBCodeBuild','IAMR-YZK-STG-WEBCodeBuild','IAMR-YZK-STG-WEBCodeBuild02','IAMR-OQS-DEV-WEBCodeBuild01','IAMR-OQS-MNT-WEBCodeBuild01','IAMR-OQS-STG-WEBCodeBuild01']
  #  :param CodeBuildSecurityGroupId: ['sg-0d3c60bf08f23206d','sg-0e842b94094c8d0d7','sg-053189344799184b4','sg-0e1ac9d9d234066ed','sg-012bdcdf9f2279f2d','sg-061e256a9d483e944','sg-036642b8d8240b67a','sg-082cbe7623eca6c48','sg-0f81aaaae2649dff2']
  #  :param DeployServiceRoleName: ['-','IAMR-TKK-DEV-WEBCodeDeploy01','IAMR-TKK-STG-WEBCodeDeploy','IAMR-IRK-MNT-WEBCodeDeploy','IAMR-IRK-MNT-WEBCodeDeploy02','IAMR-IRK-STG-WEBCodeDeploy','IAMR-YZK-STG-WEBCodeDeploy','IAMR-YZK-STG-WEBCodeDeploy02','IAMR-OQS-DEV-WEBCodeDeploy02','IAMR-OQS-MNT-WEBCodeDeploy01','IAMR-OQS-STG-WEBCodeDeploy01']
  #  :param PipelineServiceRoleName:  ['IAMR-TKK-DEV-WEBCodePipeline01','IAMR-TKK-STG-WEBCodePipeline','IAMR-IRK-MNT-WEBCodePipeline','IAMR-IRK-MNT-WEBCodePipeline02','IAMR-IRK-STG-WEBCodePipeline','IAMR-YZK-STG-WEBCodePipeline','IAMR-YZK-STG-WEBCodePipeline02','IAMR-OQS-DEV-WEBCodePipeline01','IAMR-OQS-MNT-WEBCodePipeline01','IAMR-OQS-STG-WEBCodePipeline01']
  #  :param WebInstanceRoleName: ['IAMR-TKK-DEV-WEB','IAMR-TKK-STG-WEB','IAMR-IRK-MNT-WEB','IAMR-IRK-MNT-WEB02','IAMR-IRK-STG-WEB',IAMR-YZK-DEV-WEB','IAMR-YZK-STG-WEB','IAMR-YZK-STG-WEB02','IAMR-OQS-DEV-WEB','IAMR-OQS-MNT-WEB','IAMR-OQS-MNT-WEB02','IAMR-OQS-STG-WEB','IAMR-OQS-STG-WEB02',]
  #  :param LambdaBucketName:
  #  :param LambdaZipKey:
  #  :param LOGLEVEL:
  
  MappingFilePATH:
    Type: String
    Default: 's3://s3-oqs-mt2-clf01/CICD/mappings/CLF-CICD-Mappings-LMD-From-3Kinou-To-OQS.yml'
  ProjectNumber:
    Type: String
    Description: 'example:99999'
  LargeType:
    Type: String
    Description: 'example:A'
    Default: A
  SmallType:
    Type: String
    Description: 'example:a'
    Default: a
  SystemEnvironmentName:
    Type: String
    Default: 'OQSMT2'
    AllowedValues: ['OQSDEV','OQSMNT','OQSSTG','OQSMT2','OQSMT2A','OQSMT2B']
  SystemEnvironmentName2:
    Type: String
    Default: 'TKKMT2'
    AllowedValues: ['TKKDEV','TKKMNT','TKKSTG','TKKMT2','YZKDEV','YZKMNT','YZKSTG','YZKMT2','IRKDEV','IRKMNT','IRKSTG','IRKMT2','HSKDEV','HSKMNT','HSKSTG','HSKMT2']
  LambdaBucketName:
    Type: String
    Default: 's3-oqs-mt2-clf01'
  LambdaZipKey:
    Type: String
    Default: '-'
  LOGLEVEL:
    Type: String
    Default: 'DEBUG'  
    AllowedValues: ['DEBUG','INFO']


Resources:

#-----------------LambdaLogGroup---------------#

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties: 
      KmsKeyId: !Sub 
        - 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}' 
        - KmsKeyId: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,KmsKeyId]
      LogGroupName: !Sub 
        - '/aws/lambda/LMD-${SystemNameUpper}-${EnvironmentNameUpper}-CWLtoELK-ZABBIX-MSA${ProjectNumber}-${LargeType}-${SystemName2Upper}-${EnvironmentName2Upper}' 
        - SystemNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,SystemNameUpper]
          EnvironmentNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,EnvironmentNameUpper]
          SystemName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,SystemName2Upper]
          EnvironmentName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,EnvironmentName2Upper]
      RetentionInDays: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,LogGroupRetentionInDays]

#-----------------LambdaFunction---------------#

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "CloudWatch logs To ES and Zabbix edge function"
      Environment: 
        Variables: 
          LOCAL_ES_ENDPOINT_URL: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,URL] 
          LOCAL_AWS_REGION: !Ref AWS::Region
          LOG_LEVEL: !Ref LOGLEVEL
      FunctionName: !Sub 
        - 'LMD-${SystemNameUpper}-${EnvironmentNameUpper}-CWLtoELK-ZABBIX-MSA${ProjectNumber}-${LargeType}-${SystemName2Upper}-${EnvironmentName2Upper}'
        - SystemNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,SystemNameUpper]
          EnvironmentNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,EnvironmentNameUpper]
          SystemName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,SystemName2Upper]
          EnvironmentName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,EnvironmentName2Upper]
      Handler: "lambda_function.lambda_handler"
      Architectures: 
        - "x86_64"
      Code:  
        S3Bucket: !Ref LambdaBucketName  
        S3Key: !Ref LambdaZipKey        
      MemorySize: 128
      Role: !Sub 
        - 'arn:aws:iam::${AWS::AccountId}:role/IAMR-${SystemNameUpper}-${EnvironmentNameUpper}-lambda-CWLtoZABBIX-InvokeFunction' 
        - SystemNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,SystemNameUpper]
          EnvironmentNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,EnvironmentNameUpper]      
      Runtime: "python3.9"
      Timeout: 900
      TracingConfig: 
        Mode: "PassThrough"
      VpcConfig: 
        SubnetIds: 
          - !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,Subnet1]
          - !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,Subnet2] 
          - !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,Subnet3]                    
        SecurityGroupIds: 
          - !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,LMDSecurityGroupId]  
      EphemeralStorage: 
        Size: 512

#-----------------KinesisStream---------------#

  KinesisStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: !Sub 
        - 'KDS-${SystemNameUpper}-${EnvironmentNameUpper}-MSA${ProjectNumber}-${LargeType}-${SystemName2Upper}-${EnvironmentName2Upper}'
        - SystemNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,SystemNameUpper]
          EnvironmentNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,EnvironmentNameUpper]
          SystemName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,SystemName2Upper]
          EnvironmentName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,EnvironmentName2Upper]
      RetentionPeriodHours: 24
      StreamEncryption: 
        EncryptionType: "KMS"
        KeyId: "alias/aws/kinesis"
      ShardCount: 1

#-----------------LambdaEventSourceMapping---------------#

  LambdaEventSourceMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize: 1000
      EventSourceArn: !Sub
        - 'arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/KDS-${SystemNameUpper}-${EnvironmentNameUpper}-MSA${ProjectNumber}-${LargeType}-${SystemName2Upper}-${EnvironmentName2Upper}'
        - SystemNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,SystemNameUpper]
          EnvironmentNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,EnvironmentNameUpper]
          SystemName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,SystemName2Upper]
          EnvironmentName2Upper: !FindInMap [SystemEnvironmentMapping2,!Ref SystemEnvironmentName2,EnvironmentName2Upper]
      FunctionName: !GetAtt LambdaFunction.Arn
      Enabled: true
      MaximumBatchingWindowInSeconds: 0
      ParallelizationFactor: 10
      MaximumRecordAgeInSeconds: -1
      BisectBatchOnFunctionError: false
      MaximumRetryAttempts: -1
      TumblingWindowInSeconds: 0
      StartingPosition: "LATEST"
    DependsOn: 
      - KinesisStream

#-----------------CloudWatchDestintion---------------#

  CloudWatchLogsDestination:
    Type: AWS::Logs::Destination
    Properties: 
      DestinationName: !Sub
        - DST-${SystemNameUpper}-${EnvironmentNameUpper}-MSA${ProjectNumber}-${LargeType}
        - SystemNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,SystemNameUpper]
          EnvironmentNameUpper: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,EnvironmentNameUpper]
      RoleArn: !FindInMap [SystemEnvironmentMapping,!Ref SystemEnvironmentName,CWLDestinationRoleArn]
      TargetArn: !GetAtt KinesisStream.Arn
      DestinationPolicy: >
        {"Version" : "2012-10-17","Statement" : [{"Effect" : "Allow", "Principal" : {"AWS" : "457550092927"},"Action" : "logs:PutSubscriptionFilter", "Resource" : "arn:aws:logs:ap-northeast-1:066756805702:destination:DST-OQS-MT2-*"}]}
    DependsOn: 
      - KinesisStream
