AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket
############################
# Copyrightc 2022 FUJITSU LIMITED
# FileName: CFN-OQS-MNT-AWSBatch.yml
# FileType: YAML
# OverViews: CloudFormation Template for MNT AWS Batch
# Version: 1.0
# Author: Fujitsu - tokuzumi
############################

Parameters:
  #  ## user form  ##
  #  :param BucketName: 
  #  :param VersioningConfigurationStatus: ["Enabled", "Suspended"]　
  #  :param LoggingDestinationBucketName: 
  #  :param LifecycleConfigurationStatus: 　["Enabled", "Suspended"]　
  #  :param LifecycleConfigurationPrefix: 　ライフサイクルルールのプレフィックスを指定
  #  :param LifecycleConfigurationExpirationInDays: オブジェクトの有効期限切れ
  #  :param LifecycleConfigurationNoncurrentVersionExpirationInDays: 非現行バージョン期限
  #  :param EnabledReplicationConfiguration:　["Enabled", "Suspended"]　
  #  :param KMSMasterKeyID: 
  #  ## user form  ##



  BucketName:
    Type: String 
  VersioningConfigurationStatus:
    Type: String
    AllowedValues: ["Enabled", "Suspended"]
  LoggingDestinationBucketName:
    Type: String
    Description: "- or specific bucket name" 
  LifecycleConfigurationStatus:
    Type: String
    AllowedValues: ["Enabled", "Suspended"]
  LifecycleConfigurationPrefix: 
    Type: String
  LifecycleConfigurationExpirationInDays:
    Type: Number
  LifecycleConfigurationNoncurrentVersionExpirationInDays:
    Type: Number
  EnabledReplicationConfiguration:
    Type: String
    AllowedValues: ["Enabled", "Suspended"]
  KMSMasterKeyID:
    Type: String

Conditions:
  EnabledLoggingConfiguration: !Not [ !Equals [ !Ref LoggingDestinationBucketName, "-" ] ]
  EnabledReplicationConfiguration: !Not [ !Equals [ !Ref EnabledReplicationConfiguration, "Enabled" ] ]
  EnabledLifecycleConfiguration: !Equals [ !Ref LifecycleConfigurationStatus, "Enabled" ]
  EnabledDeleteConcrrentObject: !Not [ !Equals [ !Ref LifecycleConfigurationExpirationInDays, "-" ] ]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: LogDeliveryWrite
      LoggingConfiguration: !If 
        - EnabledLoggingConfiguration
        - 
          DestinationBucketName: !Ref LoggingDestinationBucketName
          LogFilePrefix: !Sub "${LoggingDestinationBucketName}/${BucketName}-"
        - !Ref "AWS::NoValue"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration: !If 
        - EnabledLifecycleConfiguration
        - 
          Rules:
            - Id: !Sub "S3LIFE-${BucketName}"
              Prefix: !Ref LifecycleConfigurationPrefix
              Status: !Ref LifecycleConfigurationStatus
              ExpirationInDays: !If 
                - !Equals [ !Ref LifecycleConfigurationExpirationInDays, "-" ]
                - !Ref "AWS::NoValue"
                - !Ref LifecycleConfigurationExpirationInDays
              NoncurrentVersionExpirationInDays: !If 
                - !Equals [ !Ref LifecycleConfigurationNoncurrentVersionExpirationInDays, "-" ]
                - !Ref "AWS::NoValue"
                - !Ref LifecycleConfigurationNoncurrentVersionExpirationInDays
              ExpiredObjectDeleteMarker: !If 
                - EnabledDeleteConcrrentObject
                - !Ref "AWS::NoValue"
                - true
        - !Ref "AWS::NoValue"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !If 
              - !Not [ !Equals [ !Ref KMSMasterKeyID, "-" ] ]
              - !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSMasterKeyID}"
      ReplicationConfiguration: !If 
        - EnabledReplicationConfiguration
        - 
          Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/xxxxxxx"
          Rules:
            - Destination:
                Bucket: !Sub "${BucketName}-osaka"
                StorageClass: STANDARD
              Id: Backup
              Prefix: ''
              Status: Enabled
        - !Ref "AWS::NoValue"
      VersioningConfiguration:
        Status: !Ref VersioningConfigurationStatus


  # WorkItemBucketBackupRole:
  #   Type: 'AWS::IAM::Role'
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Action:
  #             - 'sts:AssumeRole'
  #           Effect: Allow
  #           Principal:
  #             Service:
  #               - s3.amazonaws.com
  # BucketBackupPolicy:
  #   Type: 'AWS::IAM::Policy'
  #   Properties:
  #     PolicyDocument:
  #       Statement:
  #         - Action:
  #             - 's3:GetReplicationConfiguration'
  #             - 's3:ListBucket'
  #           Effect: Allow
  #           Resource:
  #             - !Join
  #               - ''
  #               - - 'arn:aws:s3:::'
  #                 - !Ref RecordServiceS3Bucket
  #         - Action:
  #             - 's3:GetObjectVersion'
  #             - 's3:GetObjectVersionAcl'
  #           Effect: Allow
  #           Resource:
  #             - !Join
  #               - ''
  #               - - 'arn:aws:s3:::'
  #                 - !Ref RecordServiceS3Bucket
  #                 - /*
  #         - Action:
  #             - 's3:ReplicateObject'
  #             - 's3:ReplicateDelete'
  #           Effect: Allow
  #           Resource:
  #             - !Join
  #               - ''
  #               - - 'arn:aws:s3:::'
  #                 - !Join
  #                   - '-'
  #                   - - !Ref 'AWS::Region'
  #                     - !Ref 'AWS::StackName'
  #                     - replicationbucket
  #                 - /*
  #     PolicyName: BucketBackupPolicy
  #     Roles:
  #       - !Ref WorkItemBucketBackupRole
  